name: reto_pragma
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  http: ^1.4.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/catbreeds_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - assets/icons/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/cat-logo.png
  android: true
  ios: true
  web: false
  fullscreen: true
